- name: Common provisioning (both VPS)
  hosts: vps
  become: true
  roles:
    - user
    - packages
    - ssh
    - iptables
    - fail2ban
    - docker

- name: Install Caddy only on VPS1
  hosts: vps1
  become: true
  roles:
    - caddy

- name: Install n8n and additional tools on VPS2
  hosts: vps2
  become: true
  roles:
    - n8n_tools
