version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER={{ n8n_user }}
      - N8N_BASIC_AUTH_PASSWORD={{ n8n_password }}
    volumes:
      - n8n_data:/home/node/.n8n

  local-ai:
    image: ghcr.io/go-skynet/local-ai:latest
    container_name: local-ai
    ports:
      - "8080:8080"
    volumes:
      - ./models:/usr/local/models

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  supabase:
    image: supabase/postgres
    container_name: supabase
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: supabase_password
      POSTGRES_USER: supabase_user
      POSTGRES_DB: supabase_db
    volumes:
      - supabase_data:/var/lib/postgresql/data

  openwebui:
    image: ghcr.io/mlc-ai/web-llm:latest
    container_name: openwebui
    ports:
      - "9999:9999"
    volumes:
      - ./openwebui_data:/data

  ollama:
    image: ghcr.io/jmorganca/ollama:latest
    container_name: ollama
    ports:
      - "11400:11400"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  n8n_data:
  qdrant_data:
  supabase_data:
  ollama_data: