---
- name: Install dependencies
  apt:
    name: [debian-keyring, debian-archive-keyring, apt-transport-https]
    state: present
    update_cache: yes

- name: Add Caddy GPG key
  shell: |
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  args:
    warn: false
    creates: /usr/share/keyrings/caddy-stable-archive-keyring.gpg

- name: Add Caddy repo
  copy:
    content: |
      deb [signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian all main
    dest: /etc/apt/sources.list.d/caddy.list

- name: Install Caddy
  apt:
    name: caddy
    state: latest
    update_cache: yes

- name: Ensure Caddy is running
  service:
    name: caddy
    enabled: yes
    state: started
